<?php

namespace AppBundle\Repository;

/**
 * WorkHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
